// Generated from tools/fabric_looks.txt by tools/gen_fabriclooks.py (written from the game's own fabric textures).
using System.Collections.Generic;

namespace DressmakerAccess
{
    internal static class FabricLooks
    {
        internal static readonly Dictionary<string, string> Looks = new Dictionary<string, string>
        {
            { "WoolHoundstoothRed", "Bold red and white houndstooth check" },
            { "Silk Gradient Blue Pansy", "Fades from navy at one end through sky blue and yellow to orange" },
            { "Cotton Heron Migration", "Large dark grey herons with spread wings, flying on a cream background" },
            { "Silk Gradient Sanguine Smoke", "Fades from pale grey through deep blood red to near black" },
            { "Silk Gradient Sea Witch", "Fades from black through deep purple to soft lavender" },
            { "Silk Gradient Brandished Copper", "Fades from sage green through cream to copper and rust brown" },
            { "Silk Gradient Carmilla", "Fades from pale grey through dusky pink to deep red" },
            { "WoolArgyleBrown", "Argyle diamonds in taupe and dark teal on beige, crossed by thin red lines" },
            { "Silk Gradient Sunset", "Fades from deep navy through purple and hot pink to orange" },
            { "Cotton Radishing Print", "Carrots, radishes, beetroot and leafy greens scattered on a pale yellow background" },
            { "Cotton Embroidered Diamond Red", "Shimmering white embroidery of diamonds, flowers and twisted cords on deep red" },
            { "Sequin Gradient Protea", "Fades from pale pink through dusky rose to dark burgundy" },
            { "Silk Gradient Meadow Flower", "Fades from dark green through sage to pale pink and raspberry" },
            { "CottonPeonyRows", "Rows of embroidered magenta peonies with teal leaves, on winding brown vines over cream" },
            { "CottonGinghamBlue", "Blue and white gingham check" },
            { "Silk Gradient Grey-dient", "Fades from black through grey to pale silver" },
            { "Silk Gradient Fairy Floss", "Fades from red through pink and purple to deep navy" },
            { "CottonFloralSilhouette Purple", "Cream daisies and curling leaves all over a purple background" },
            { "CottonFloralSilhouette Orange", "Cream daisies and curling leaves all over a terracotta background" },
            { "CottonFloralSilhouette Blue", "Cream daisies and curling leaves all over a blue background" },
            { "Lace French Red", "Lace of swirling, curling leaves and scrolls over a fine net" },
            { "Silk Gradient Blue Flame", "Fades from deep navy through purple and red to golden orange" },
            { "CottonGinghamGreen", "Sage green and white gingham check" },
            { "WoolArgyleGreen", "Argyle diamonds in olive and dark green on grey-beige, crossed by thin purple lines" },
            { "CottonGinghamWarmBlack", "Dark brown and tan gingham check" },
            { "Lace Royal Blue", "Lace of swirling, curling leaves and scrolls over a fine net" },
            { "Lace Royal Purple", "Lace of swirling, curling leaves and scrolls over a fine net" },
            { "CottonFloralLibertyGrey", "Small, densely packed flowers in muted lilac, sage and cream on a dark grey background" },
            { "Cotton Forget Me Not Red", "Tiny red, yellow and lilac wild flowers on trailing green stems, on off-white" },
            { "CottonFloralLibertyOrange", "Small, densely packed flowers in orange, peach and pink on an olive background" },
            { "Cotton Gingham Meadow", "Olive and cream gingham check" },
            { "CottonBlossomsOnMidnightEmbroidered", "Bands of embroidered pink and orange blossoms with gold borders, across a midnight black background" },
            { "Silk Paisley Purple", "Large, swirling paisley in pink, aqua and lilac on a dark grey-purple background" },
            { "Cotton Repeating Marigolds", "Large stylised navy flowers on green stems, spaced out on a bright orange background" },
            { "Cotton Spring Bouquet", "Sprays of pink roses, orange berries, white daisies and ferns on cream" },
            { "Cotton Whimsy Ditsy", "Pink, yellow, orange and blue flowers with leaves, scattered on pale duck-egg blue" },
            { "Velvet Burnout Capricorn", "Burnout velvet: a dark grey pattern of goats, fans and scrolls on black" },
            { "Cotton Embroidered Eclectic Scalloped Winter", "Dense folk embroidery of tiny flowers, scallops and diamonds in cream, red and gold on navy" },
            { "WoolArgyleBlue", "Argyle diamonds in slate and navy blue on grey, crossed by thin brown lines" },
            { "CottonScandiFlowers", "Simple folk-style red tulips on teal stems, spaced out on mustard yellow" },
            { "CottonFloralPainterly", "Large, flowing sage-green leaves with a few gold and pink flowers on cream" },
            { "Silk Gradient Pastel Sunrise", "Fades from pale lilac through dusky pink to soft orange" },
            { "Silk Gradient Radioactive", "Fades from near black through dark teal to bright jade green" },
            { "Cotton Strawberry Thief", "Rows of rabbits and strawberries on cream, between bands of pink zigzag" },
            { "Sequin Gradient Desert Dawn", "Fades from sandy gold through mauve to dark brown" },
            { "SilkPatriceOrchil", "A scattered pattern of teardrop petals and curls" },
            { "SilkPatricendigo", "A scattered pattern of teardrop petals and curls" },
            { "SilkFloralPurple", "A scattered pattern of teardrop petals and curls" },
            { "Silk Gradient Frangipani", "Fades from soft periwinkle blue through white to pale yellow" },
            { "CottonKaleidoscopeBlue", "Tile-like kaleidoscope medallions in teal, blue and purple on dark green" },
            { "Cotton Friends of a Feather", "Geese, ducks and hens with little flower sprigs on pale cream" },
            { "CottonStrawberryFieldsMonochrome", "Watercolour strawberries on curling green vines, on soft pink" },
            { "CottonKaleidoscopePink", "Tile-like kaleidoscope medallions in pink, aqua and grey on dark plum" },
            { "CottonKaleidoscopeRed", "Tile-like kaleidoscope medallions in red, orange and olive on dark brown" },
            { "SilkEmbellished Swirling Citrine", "Embellished with circles of tiny dots, swirling over each other all over" },
            { "Sequins Styx", "Sequins laid in swirling circles of tiny dots" },
            { "Sequins Sanguine Dreams", "Sequins laid in swirling circles of tiny dots" },
            { "Sequins Dante Swirling", "Sequins laid in swirling circles of tiny dots" },
            { "Sequin Mica", "Sequins laid in swirling circles of tiny dots" },
            { "SilkFloralScrollClassicLight", "Brown scrolling leaves and curls on pale gold" },
            { "Silk Gradient Parrot FIsh", "Fades from magenta through royal blue and teal to dark green" },
            { "Cotton Celeste", "Golden starbursts, like suns and fireworks, on a dark brown background" },
            { "SilkDesertRain", "Stripes of sage, rust and dark green, with fine rows of beads" },
            { "Sequin Gradient Undine", "Fades from olive green through slate blue to navy" },
            { "Sequin Gradient Jellyfish", "Fades from teal through near black to deep burgundy" },
            { "Silk Gradient Golden Dawn", "Fades from soft peach through orange to rust red" },
            { "WoolPlaid Green", "Dark green tartan with lines of sage and mustard" },
            { "Silk Paisley Red", "Large, swirling paisley in red, pink and cream on dusky purple" },
            { "CottonForgetMeNots", "Small blue forget-me-nots on trailing green stems, on pale cream" },
            { "VelvetAlexandriaPrint", "Large dark olive flowers and leaves printed on a sage green background" },
            { "Silk Gradient Water Lily", "Fades from olive green to teal" },
            { "Sequin Stalactite", "Rows of round sequins in pastel pink, mint and yellow" },
            { "Sequin Peacock", "Rows of round sequins in pastel pink, mint and yellow" },
            { "WoolPinstripesWhite", "Dark charcoal wool with fine pinstripes" },
            { "Velvet Burnout Dahlia Damask", "Burnout velvet: a large dark purple damask of dahlias and scrolls on lilac grey" },
            { "Cotton Midnight Garden Print", "Dense small flowers in red, cream and blue among green leaves, on near black" },
            { "Silk Leaf Print Black", "Large grey feathery leaves printed on charcoal" },
            { "Cotton Rustic Diamond Embroidered", "Cream embroidered diamonds of dots and small flower medallions on deep brick red" },
            { "WoolPlaid Red", "Rust red and brown tartan with tan lines" },
            { "Cotton Check Ochre", "Large windowpane check in ochre, tan and caramel" },
            { "CottonKaleidoscopeGreen", "Tile-like kaleidoscope medallions in olive, teal and grey on dark charcoal green" },
            { "CottonSerpentPrintRed", "Golden serpents coiling among leaves and lilies on deep plum red" },
            { "Sequin Gradient Artemis", "Fades from slate grey through mauve to dusky red" },
            { "Cotton Autumnal Vine Border Print", "Plain warm beige, with bands of red and blue vines along the edges" },
            { "Silk Gradient Pelagic", "Fades from deep navy to soft aqua blue" },
            { "Silk Gradient Aphrodite", "Fades from dusty rose through mauve to dark plum" },
            { "Silk Gradient Snowflake", "Fades from silver grey through ice blue to cornflower blue" },
            { "Velvet Burnout Medusa", "Burnout velvet: dark olive serpents and lilies on a grey-green background" },
            { "VelvetTajMahalFloral", "Dusky pink stylised lilies and flowers in rows on deep crimson brown" },
            { "Cotton Check Rainbow Magic", "A patchwork check of small squares in muted rainbow colours: rust, olive, mustard, slate and rose" },
            { "Sequins Gradient Rainbow", "Fades from coral through orange and gold to sage green" },
            { "VelvetFloralBurnout Green", "Burnout velvet: an ornate pattern of pink flowers, orange dots and paisley on deep green" },
            { "Cotton Cross Patty Embroidered Yellow", "Folk embroidery of orange stepped diamonds and little red flowers on stems, with dashed white lines, on mustard" },
            { "SilkEmbellished Geometric Gold", "An ornate tile pattern of gold, cream and red medallions and flowers" },
            { "SilkBlockPrintDiamondYellow", "Hand-stamped flowers of teardrop petals around a dot, in rows" },
            { "SilkBlockPrintDiamond Green", "Hand-stamped flowers of teardrop petals around a dot, in rows" },
            { "SilkBlockPrintDiamond", "Hand-stamped flowers of teardrop petals around a dot, in rows" },
            { "CottonSerpentPrintGreen", "Golden serpents coiling among leaves and lilies on dark green" },
            { "CottonFloralEmbroidered", "White daisies and small red rosebuds scattered on sky blue" },
            { "Cotton Cross Patty Embroidered Green", "Folk embroidery of red stepped diamonds and little flowers on stems, with dashed white lines, on grass green" },
            { "WoolHoundstoothCool", "Brown, grey and beige houndstooth check" },
            { "VelvetBirdsongTeal", "Golden birds among leafy branches and flowers on teal" },
            { "Cotton Lucky Day", "Large four-leaf clovers and flowers in soft greens, peach and teal" },
            { "Sequin Gradient Galaxy", "Fades from near black through steel blue to deep red" },
            { "Cotton Magenta Floral Block Print", "Pink leaves and berry-like flowers on deep plum" },
            { "VelvetTajMahalFloral Forest", "Sage green stylised lilies and flowers in rows on deep forest green" },
            { "Silk Gradient Lavender Field", "Fades from teal through soft blue to lavender" },
            { "CottonPeonyRows Purple", "Rows of embroidered purple peonies with teal leaves, on winding plum vines over grey" },
            { "Cotton Gingham Dijon", "Mustard yellow and soft pink gingham check" },
            { "CottonMulticolouredFloral", "Small sage, blue and gold flowers and leaves scattered on cream" },
            { "CottonBlackFloral Midnight", "Small flowers and trailing sprigs scattered all over, in silver on midnight" },
            { "CottonBlackFloral Crimson", "Small flowers and trailing sprigs scattered all over, in gold on crimson" },
            { "CottonBlackFloral", "Small flowers and trailing sprigs scattered all over, in gold on black" },
            { "Silk Gradient Unicorn", "Fades from pink through lilac to soft aqua" },
            { "LinenPolka Black", "White polka dots, spaced well apart, on black" },
            { "CottonDaisyDitsyPrint", "Coral and red daisies with leaves and little dots on chocolate brown" },
            { "Silk Paisley Plum Brocade", "A brocade of swirling paisley and curls in lilac and cream" },
            { "Silk Paisley Emerald Brocade", "A brocade of swirling paisley and curls in green and cream" },
            { "CottonNadineFloralDiamondRed", "Small peach flowers and green sprigs in trellis rows on rust red" },
            { "SilkFloralScrollClassicDark", "Cream scrolling leaves and curls on dark gold-brown" },
            { "Cotton Embroidered Diamond Teal", "Pale embroidery of diamonds, flowers and twisted cords on teal" },
            { "VelvetBirdsongMauve", "Blue birds among leafy branches and flowers on deep mauve" },
            { "VelvetTajMahalFloral Bloom", "Dusky pink stylised lilies and flowers in rows on deep plum" },
            { "Cotton Check Rhubarb & Custard", "Rhubarb red and custard yellow check" },
            { "SilkEmbellished Geometric Green", "An ornate tile pattern of olive green, red and cream medallions" },
            { "Silk Gradient Ember", "Fades from near black to glowing rust orange" },
            { "Cotton Sunset Botanicals", "Dense golden flowers and curling leaves on burnt orange" },
            { "CottonNadineFloralDiamondBlue", "Small pink flowers and teal sprigs in trellis rows on mint" },
            { "SilkFloralBrocade", "Small red flowers and green leaves on a cream crackle background" },
            { "Silk Paisley Yellow", "Large, swirling paisley in golden yellows" },
            { "CottonStemmedHydrangea White", "Hydrangea heads, long leaves and small orange flowers on a linen-textured background" },
            { "CottonStemmedHydrangea", "Hydrangea heads, long leaves and small orange flowers on a linen-textured background" },
            { "Sequin Gradient Beach Bliss", "Fades from golden yellow through peach to coral red" },
            { "CottonDiamondPrintYellow", "Little pointed leaves arranged in open diamond rings, spaced over the background" },
            { "CottonDiamondPrint Purple", "Little pointed leaves arranged in open diamond rings, spaced over the background" },
            { "CottonDiamondPrint", "Little pointed leaves arranged in open diamond rings, spaced over the background" },
            { "SilkContinuousFloralDaintyBlue", "Golden trailing vines with small leaves and flowers on mid blue" },
            { "Shimmer Silk Solar Flare", "An iridescent silk whose colour shimmers and shifts" },
            { "Shimmer Silk Cosmos", "An iridescent silk whose colour shimmers and shifts" },
            { "CottonNadineFloralDiamondYellow", "Small orange and blue flowers and green sprigs in trellis rows on cream" },
            { "Cotton Winter Vine Border Print", "Plain dusky lilac, with bands of blue and green vines along the edges" },
            { "_CottonVictorianPattern", "Pale blue fleurs-de-lis and small lilac flowers inside a turquoise trellis, on white" },
            { "SilkEmbellished Geometric Purple", "An ornate tile pattern of purple, magenta and olive medallions" },
            { "VelvetBirdsongAmber", "Rust birds among leafy branches and flowers on amber gold" },
            { "Cotton Spring Vine Border Print", "Plain soft mint, with bands of pink and green vines along the edges" },
            { "Lace Black", "Lace of fan-shaped flowers and medallions in rows, over a fine net" },
            { "WoolPinstripesBrown", "Warm brown wool with fine pinstripes" },
            { "Lace Overlay Red Silk", "Lace of fan-shaped flowers, medallions and leaves over silk" },
            { "Lace Overlay Pink", "Lace of fan-shaped flowers, medallions and leaves over silk" },
            { "LinenFloral", "Large tan flowers and curling leaves on terracotta" },
            { "CottonStemmedHydrangea Pink", "Pink hydrangea heads, long leaves and small flowers on a soft pink linen-textured background" },
            { "WoolPlaid Black", "Black tartan with fine lines of plum and taupe" },
            { "Lace Floral French Black", "Lace of large flowers and curling leaves over a fine net" },
            { "VelvetMushroomPolka", "Small white polka dots on red, like a toadstool cap" },
            { "Lace White", "Lace of large flowers and curling leaves over a fine net" },
            { "Lace Mustard", "Lace of large flowers and curling leaves over a fine net" },
            { "Lace Forest Green", "Lace of large flowers and curling leaves over a fine net" },
            { "Lace Brilliant Red", "Lace of large flowers and curling leaves over a fine net" },
            { "Lace Brilliant Pink", "Lace of large flowers and curling leaves over a fine net" },
            { "CottonDarkPurpleFloral", "Sage green and gold flowers and leaves on dusky purple" },
            { "Cotton Gingham Sky", "Sky blue, grey and sand gingham check" },
            { "Shimmer Silk Galaxy", "An iridescent silk whose colour shimmers and shifts" },
            { "WoolHoundstoothBlack", "Black and charcoal houndstooth check" },
            { "WoolPinstripesBlue", "Greyish blue wool with fine pinstripes" },
            { "LinenRhiannonTrailingFloralBronze", "Fine bronze trailing flowers and branches on sandy beige" },
            { "Velvet Crushed Mirage", "Crushed velvet in mottled patches of orange, rust, blue and grey" },
            { "Velvet Siren", "Crushed velvet in mottled patches of blue, green and purple" },
            { "CottonNadineFloralDiamondPink", "Small yellow and blue flowers and coral sprigs in trellis rows on peach" },
            { "VelvetStarryNight", "Gold stars and twinkles of different sizes on dark navy" },
            { "Sequin Gradient Mermaid Dream", "Fades from dusky mauve to grey-green" },
            { "WoolArgyleBlack", "Argyle diamonds in charcoal and black, crossed by thin olive lines" },
            { "SilkWhiteFloralEmbroidered", "Embroidered with roses, small flowers and leaves all over" },
            { "SilkPinkFloralEmbroidered", "Embroidered with roses, small flowers and leaves all over" },
            { "SilkFloralEmbroidered Yellow", "Embroidered with roses, small flowers and leaves all over" },
            { "SilkFloralEmbroidered Black", "Embroidered with roses, small flowers and leaves all over" },
            { "LinenContinuousPoppy", "Pink poppies among long green leaves on pale green linen" },
            { "SilkContinuousRoseBrocade", "Large ivory flowers and sprigs on icy grey-blue" },
            { "CottonAbstractPastelSplashes", "Painterly streaks and splashes of pink, lilac and aqua" },
            { "CottonPastelFloral", "Small pastel flowers in yellow, pink and sage on cream" },
            { "VelvetTechnicolourPurpleOrange", "Velvet in mottled, blended patches of purple, magenta and orange" },
            { "Sequin Shooting Star", "Rows of round sequins in pastel pink, yellow and blue" },
            { "VelvetFloralBurnout Purple", "Burnout velvet: an ornate pattern of purple flowers, orange scrolls and dots on charcoal" },
            { "CottonPlaidPink", "Soft pink plaid of wide and narrow stripes on pale blush" },
            { "LaceSnowPetal", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "LacePurplePetal", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "Lace Teal", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "Lace Subdued Purple", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "Lace Subdued Blue", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "Lace Silver", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "Lace Pastel Yellow", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "Lace Pastel Purple", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "Lace Pastel Pink", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "Lace Pastel Blue", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "Lace Gold", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "Lace Dusty Pink", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "Lace Bronze", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "Lace Absynthe", "Lace of roses, little flowers and leafy sprigs over a fine net" },
            { "Silk Pink Carnation Print", "A large white damask of carnations and scrolls on soft pink" },
            { "CottonStrawberryFieldsPrint", "Strawberries, flowers and curling vines, tone on tone, on bright coral red" },
            { "VelvetBlossomingBlancEmbellished", "Beaded paisleys and tiny flowers in taupe and pink on pale grey" },
            { "CottonElegantPlumFoliage", "Small dark leaves, vines and cream berries on plum" },
            { "Silk Diamond Filigree Violet", "A tone-on-tone filigree of leafy scrolls and flower shapes" },
            { "Silk Diamond Filigree Magenta", "A tone-on-tone filigree of leafy scrolls and flower shapes" },
            { "Silk Diamond Filigree Crimson", "A tone-on-tone filigree of leafy scrolls and flower shapes" },
            { "Silk Diamond Filigree", "A tone-on-tone filigree of leafy scrolls and flower shapes" },
            { "Silk Leaf Print Green", "Dense long leaves in olive, gold and green" },
            { "Shimmer Silk Scarab", "An iridescent silk whose colour shimmers and shifts" },
            { "Shimmer Silk Blushing Skies", "An iridescent silk whose colour shimmers and shifts" },
            { "VelvetTechnicolourYellowGreen", "Velvet in mottled, blended patches of lime green, teal and gold" },
            { "SilkContinuousFloralDaintyPurple", "Pale trailing vines with small leaves and flowers, tone on tone" },
            { "SilkContinuousFloralDaintyPink", "Pale trailing vines with small leaves and flowers, tone on tone" },
            { "SilkContinuousFloralDaintyBeige", "Pale cream trailing vines with small leaves and flowers on beige" },
            { "LinenVictorian Light", "A raised trellis of ogee shapes and little fleurs, in copper on dark brown" },
            { "LinenVictorian", "A raised trellis of ogee shapes and little fleurs, in copper on dark brown" },
            { "Silk Flower Hibiscus Blue", "Large overlapping hibiscus petals in royal and navy blue" },
            { "CottonRectanglePattern Olive", "Small soft rectangles and diamonds in rows on olive green" },
            { "SilkBridgetSilkBrocade", "A brocade of curling white vines and feathery leaves, tone on tone" },
            { "VelvetStarry Night Blue", "Gold stars and twinkles of different sizes on navy blue" },
            { "Silk Leaf Print Teal", "Dense long leaves in teal, olive and brown" },
            { "Silk Flower Orange", "Large overlapping hibiscus petals in gold and orange, outlined in red" },
            { "VelvetStarryNightRed", "Gold stars and twinkles of different sizes on dark scarlet brown" },
            { "CottonDotDesign Pink", "Small four-petal flower dots, spaced well apart" },
            { "CottonDotDesign Brown", "Small four-petal flower dots, spaced well apart" },
            { "CottonDotDesign Blue", "Small four-petal flower dots, spaced well apart" },
            { "CottonDotDesign Red", "Small four-petal flower dots, spaced well apart" },
        };
    }
}
